### PR TITLE
Add functions to fetch individual token kinds

### PR DESCRIPTION
**Pull request by dmosites**

### CODE REVIEW

**Review by piersss — CHANGES_REQUESTED** [review]
1. `logoURI` is missing.
2. So far the only data I get from extensions is:
```
trait_type: "item"
value:  "Reveal Soon"
```
So it's not adding anything data that's actually useful. Or are you getting something else?

3. Some way to auto detect what's the tokenKind would be useful. So we can use `scrapeToken` for any token.

**Review by piersss — CHANGES_REQUESTED** [review]
I tested ERC721 and ERC1155. 0x0e5afd99ab6234fe73c76ea1a78a48e27a69dba6 and 0x0Fe66E38e81DdE40134454D7af433fE6dDB537d9 . Chain id 1.

1. Tested `getERC721FromContract`

Still only get these attributes: 
`{trait_type: 'item', value: 'Reveal Soon'}`

2. Tested `getERC1155FromContract`. Getting way more unqiue data with this one, nice!  🥳 

3. Tested `getTokenFromContract`

```
index.js:1 Error: invalid BigNumber value (argument="value", value=undefined, code=INVALID_ARGUMENT, version=bignumber/5.7.0)
    at Logger.makeError (index.ts:269:1)
    at Logger.throwError (index.ts:281:1)
    at Logger.throwArgumentError (index.ts:285:1)
    at BigNumber.from (bignumber.ts:289:1)
    at NumberCoder.encode (number.ts:25:1)
    at array.ts:71:1
    at Array.forEach (<anonymous>)
    at pack (array.ts:54:1)
    at TupleCoder.encode (tuple.ts:54:1)
    at AbiCoder.encode (abi-coder.ts:111:1)
    at Interface._encodeParams (interface.ts:323:1)
    at Interface.encodeFunctionData (interface.ts:376:1)
    at index.ts:228:1
    at Generator.next (<anonymous>)
    at fulfilled (index.ts:2:1)
```

4. Tokenuri still missing

**Comment by dmosites** [comment]
I've changed `extensions` to just include `kind`, `id` (if relevant), and `metadata` (populated with response from `tokenURI`/ `uri` endpoint). If it feels like we're shoehorning all this into `TokenInfo` we could find or create a more appropriate type.

1. there's only one "attribute" for that token. the full result on my end for `getERC721FromContract(provider, '0x0e5afd99ab6234fe73c76ea1a78a48e27a69dba6', '1')` is:
```
{
  chainId: 1,
  address: '0x0e5afd99ab6234fe73c76ea1a78a48e27a69dba6',
  name: 'FishMafia',
  symbol: 'FM',
  decimals: 0,
  extensions: {
    kind: '0x80ac58cd',
    id: '1',
    metadata: {
      name: 'FishMafia #1',
      description: 'Fully animated pixel mafia | 0% royalties | CC0',
      image: 'ipfs://QmYVTo4WgnoFskJNa3N17PadVzGNCL23VGwXWy8zCT8fFX',
      attributes: [ { trait_type: 'item', value: 'Reveal Soon' } ]
    }
  }
}
```
2. good news!
3. what were your arguments for `getTokenFromContract`? if it detects ERC721 or ERC1155 it expects an `id` and will throw. (a descriptive error has since been added)
4. what are you expecting for `tokenURI`? it's an ERC721 property, from which JSON is fetched and spread into `extensions.metadata`. if you're looking for `TokenInfo.logoURI` those are not standard ERC20. I'll explore any metadata extensions but it won't always be populated.

FYI going forward you can just use `getTokenFromContract`.

**Comment by piersss** [comment]
Ok all good, I indeed forgot to use token id with `getTokenFromContract`.

One last issue: Erc20 stopped working for some reason. When using binance coin `0x2170ed0880ac9a755fd29b2688956bd959f933f8` I get this:

```
index.js:1 Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="name()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
    at Logger.makeError (index.ts:269:1)
    at Logger.throwError (index.ts:281:1)
    at Interface.decodeFunctionResult (interface.ts:427:1)
    at Contract.<anonymous> (index.ts:400:1)
    at Generator.next (<anonymous>)
    at fulfilled (index.ts:2:1)
```

**Review by piersss — APPROVED** [review]
LGTM

**Pull request merged**
